// This file is auto-generated by Payload
import { CloudinaryClientUploadHandler } from '@jhb.software/payload-cloudinary-plugin/client'

export const importMap = {
  '@jhb.software/payload-cloudinary-plugin/client#CloudinaryClientUploadHandler': CloudinaryClientUploadHandler,
}
